In [2]:
import numpy as np 
import pandas as pd

### 1. NumPy's version

In [3]:
np.__version__

'1.21.5'

### 2. Read Data with Pandas 

In [43]:
# data_file_path = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv'
car_data = pd.read_csv('../../MLzoomcamp/data.csv')
car_data.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

### 2. Number of rows

In [5]:
car_data.shape[0]

11914

### 3. Most popular car manufacturers (Top 3) 

In [8]:
make =pd.Index(car_data.Make)
make 

Index(['BMW', 'BMW', 'BMW', 'BMW', 'BMW', 'BMW', 'BMW', 'BMW', 'BMW', 'BMW',
       ...
       'BMW', 'BMW', 'Acura', 'Acura', 'Acura', 'Acura', 'Acura', 'Acura',
       'Acura', 'Lincoln'],
      dtype='object', name='Make', length=11914)

In [17]:
make.value_counts()[:3]
#Top 3 :
#1 Chevrolet        1123 car
#2 Ford              881 car
#3 Volkswagen        809 car

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

### 4.  The number of unique Audi car models in the dataset

In [25]:
audi_cars = car_data.loc[car_data.Make == "Audi"] 
print(audi_cars.Model.unique())
len(audi_cars.Model.unique()) #  The number of unique Audi car models is : 34 

['100' '200' '80' '90' 'A3' 'A4 allroad' 'A4' 'A5' 'A6' 'A7' 'A8'
 'allroad quattro' 'allroad' 'Cabriolet' 'Coupe' 'Q3' 'Q5' 'Q7' 'R8'
 'RS 4' 'RS 5' 'RS 6' 'RS 7' 'S3' 'S4' 'S5' 'S6' 'S7' 'S8' 'SQ5' 'TT RS'
 'TT' 'TTS' 'V8']


34

### 5. Number of columns having missig values

In [27]:
car_data.isnull().sum() #  There are 5 columns having  missing values 

# isnull() function Detects missing values 
# sum() fuction shows the sum of lissing values in each columns
# sum =0 it means that columns doesn't have any missing values 

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

### 6.  Does the median value change after filling missing values?

In [187]:
medHP_before = car_data['Engine Cylinders'].median()
medHP_before

6.0

In [270]:
mode_EnCy =car_data['Engine Cylinders'].mode()[0]
mode_EnCy

4.0

In [271]:
car_data['Engine Cylinders'].fillna(mode_EnCy , inplace = True )


In [272]:
medHP_after = car_data['Engine Cylinders'].median()
medHP_after  # it hassn't change  Response : No 

6.0

### 7. What's the value of the first element of w ?

In [29]:
lotus_cars = audi_cars = car_data.loc[car_data.Make == "Lotus"] 
lotus_cars.head()

Make  Model  Year             Engine Fuel Type  Engine HP  \
3912  Lotus  Elise  2009  premium unleaded (required)      189.0   
3913  Lotus  Elise  2009  premium unleaded (required)      218.0   
3914  Lotus  Elise  2009  premium unleaded (required)      189.0   
3915  Lotus  Elise  2010  premium unleaded (required)      189.0   
3916  Lotus  Elise  2010  premium unleaded (required)      218.0   

      Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
3912               4.0            MANUAL  rear wheel drive              2.0   
3913               4.0            MANUAL  rear wheel drive              2.0   
3914               4.0            MANUAL  rear wheel drive              2.0   
3915               4.0            MANUAL  rear wheel drive              2.0   
3916               4.0            MANUAL  rear wheel drive              2.0   

              Market Category Vehicle Size Vehicle Style  highway MPG  \
3912  Exotic,High-Performance      Compact   Convertible           27   
3913  Exotic,High-Performance      Compact   Convertible           26   
3914  Exotic,High-Performance      Compact   Convertible           27   
3915  Exotic,High-Performance      Compact   Convertible           27   
3916  Exotic,High-Performance      Compact   Convertible           26   

      city mpg  Popularity   MSRP  
3912        21         613  43995  
3913        20         613  54990  
3914        21         613  47250  
3915        21         613  47250  
3916        20         613  54990

In [33]:
lotus_cars  = lotus_cars[["Engine HP", "Engine Cylinders"]]
lotus_cars

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [34]:
lotus_cars.drop_duplicates(inplace = True)
lotus_cars

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [35]:
x = lotus_cars.to_numpy()
x

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [37]:
XTX = x.T.dot(x)  #This function returns the dot product of two arrays. For 2-D vectors, it is the equivalent to matrix multiplication.
                   #For 1-D arrays, it is the inner product of the vectors. 
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [38]:
XTX_inv = np.linalg.inv(XTX)
# numpy.linalg.inv() function calculates the inverse of a matrix. 
#The inverse of a matrix is such that if it is multiplied by the original matrix, it results in identity matrix.
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [39]:
y =np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

In [40]:
XTXXT = XTX_inv.dot(x.T)
XTXXT

array([[-1.31950096e-03,  2.84443321e-04,  2.29134897e-04,
        -4.18763778e-03,  4.46417989e-03, -2.39406462e-03,
         1.42221660e-03,  2.44147184e-03,  1.50122864e-03],
       [ 8.60893170e-02,  7.36567735e-04,  3.67976598e-03,
         2.54588185e-01, -2.13748621e-01,  1.51207962e-01,
        -5.18727169e-02, -1.14048164e-01, -6.40137937e-02]])

In [41]:
w = XTXXT.dot(y)
print (w)
print(w[0])  # The first value of w is :  4.59494481

[  4.59494481 -63.56432501]
4.594944810094579
